### ISSUE TITLE
Streamlit RuntimeError with default leafmap module

### ISSUE THREAD

**Issue by zxdawn** [opengeos/leafmap#464]
### Environment Information

-   leafmap version: 0.21.0
-   Python version: 3.10
-   Operating System: Mac

### Description

The default leafmap module can't work well with Streamlit, but foliumap works.

### What I Did

```
import streamlit as st
import leafmap
#import leafmap.foliumap as leafmap

landsat_url = (
    'https://drive.google.com/file/d/1EV38RjNxdwEozjc9m0FcO3LFgAoAX1Uw/view?usp=sharing'
)
leafmap.download_file(landsat_url, 'test.tif', unzip=False, overwrite=True)

m = leafmap.Map()
m.add_raster('test.tif', band=1, colormap='terrain', layer_name='DEM')

col1, col2 = st.columns([7, 3])

with col1:
        m.to_streamlit()
```

### Error

```
2023-06-07 20:48:38.297 Uncaught app exception
Traceback (most recent call last):
  File "/Users/xinz/miniconda3/envs/streamlit/lib/python3.10/site-packages/streamlit/runtime/scriptrunner/script_runner.py", line 565, in _run_script
    exec(code, module.__dict__)
  File "/Users/xinz/Documents/github/enmap/app/test/test_raster.py", line 10, in <module>
    m.add_raster('test.tif', band=1, colormap='terrain', layer_name='DEM')
  File "/Users/xinz/miniconda3/envs/streamlit/lib/python3.10/site-packages/leafmap/leafmap.py", line 1898, in add_raster
    self.zoom_to_bounds(bounds)
  File "/Users/xinz/miniconda3/envs/streamlit/lib/python3.10/site-packages/leafmap/leafmap.py", line 242, in zoom_to_bounds
    self.fit_bounds([[bounds[1], bounds[0]], [bounds[3], bounds[2]]])
  File "/Users/xinz/miniconda3/envs/streamlit/lib/python3.10/site-packages/ipyleaflet/leaflet.py", line 2622, in fit_bounds
    asyncio.ensure_future(self._fit_bounds(bounds))
  File "/Users/xinz/miniconda3/envs/streamlit/lib/python3.10/asyncio/tasks.py", line 615, in ensure_future
    return _ensure_future(coro_or_future, loop=loop)
  File "/Users/xinz/miniconda3/envs/streamlit/lib/python3.10/asyncio/tasks.py", line 634, in _ensure_future
    loop = events._get_event_loop(stacklevel=4)
  File "/Users/xinz/miniconda3/envs/streamlit/lib/python3.10/asyncio/events.py", line 656, in get_event_loop
    raise RuntimeError('There is no current event loop in thread %r.'
RuntimeError: There is no current event loop in thread 'ScriptRunner.scriptThread'.
```

**Comment by giswqs** [comment]
Streamlit doesn't support Localtileserver. Adding local raster won't work with Streamlit.

**Comment by zxdawn** [comment]
Ha, then is it possible to use `add_raster` and `add_velocity` at the same time with streamlit? I see `The folium plotting backend does not support this function.` in the source code of foliumap.

**Comment by giswqs** [comment]
Correct. Streamlit only supports add_cog_layer()

**Comment by zxdawn** [comment]
Got it. Then this [tutorial](https://ocefpaf.github.io/python4oceanographers/blog/2015/11/16/folium_quiver/) of plotting wind quiver is useful!
