### ISSUE TITLE
add_raster doesn't work for epsg:32645

### ISSUE THREAD

**Issue by zxdawn** [opengeos/leafmap#547]
### Environment Information

-   leafmap version: 0.20.3
-   Python version: 3.10.12
-   Operating System: Mac M1

### Description

The `add_raster` doesn't work for epsg:32645 with transform. Here's the [test data](https://github.com/opengeos/leafmap/files/12596364/test.tif.zip).

### What I Did

I have plotted the tiff file using cartopy and it works well:

```
import rioxarray
import xarray as xr
import matplotlib.pyplot as plt
from cartopy.crs import epsg as ccrs_from_epsg, PlateCarree

test = xr.open_dataset('/Users/xinz/Downloads/test.tif')

geoTransform = test.rio.transform()
minx = geoTransform[0]
maxy = geoTransform[3]
maxx = minx + geoTransform[1] * len(test.x)
miny = maxy + geoTransform[5] * len(test.y)
extent = [minx, maxx, miny, maxy]

test_crs = ccrs_from_epsg(test.rio.crs.to_epsg())

print(test.rio.crs.to_proj4())

fig, ax = plt.subplots(subplot_kw={'projection': PlateCarree()})

ax.set_extent(extent, crs=test_crs)

ax.imshow(test['band_data'].transpose(..., 'band'),
            origin='upper',
            transform=get_cartopy_crs_from_epsg(test.rio.crs.to_epsg()),
            extent=extent
            )

gl = ax.gridlines(draw_labels=True, dms=False, color = 'gray', linewidth=1, alpha=0.5,  linestyle='--')
gl.top_labels = False
gl.right_labels = False
```
<img width="527" alt="image" src="https://github.com/opengeos/leafmap/assets/30388627/2b7c97dd-1a2f-4fb8-bfed-9165187006cc">

Then, I tried to use `add_raster` to overlay the tiff on map:
```
import leafmap.foliumap as leafmap

m = leafmap.Map()
m.add_raster('/Users/xinz/Downloads/test.tif', nodata=0)
```

I got this error:
<details>
<summary>Click to see error</summary>

```
[2023-09-13 12:24:32,502] ERROR in app: Exception on [/api/bounds](https://file+.vscode-resource.vscode-cdn.net/api/bounds) [GET]
Traceback (most recent call last):
  File "/Users/xinz/miniconda3/envs/enpt/lib/python3.10/site-packages/flask/app.py", line 1517, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/xinz/miniconda3/envs/enpt/lib/python3.10/site-packages/flask/app.py", line 1503, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/Users/xinz/miniconda3/envs/enpt/lib/python3.10/site-packages/flask_restx/api.py", line 404, in wrapper
    resp = resource(*args, **kwargs)
  File "/Users/xinz/miniconda3/envs/enpt/lib/python3.10/site-packages/flask/views.py", line 84, in view
    return current_app.ensure_sync(self.dispatch_request)(*args, **kwargs)
  File "/Users/xinz/miniconda3/envs/enpt/lib/python3.10/site-packages/flask_restx/resource.py", line 46, in dispatch_request
    resp = meth(*args, **kwargs)
  File "/Users/xinz/miniconda3/envs/enpt/lib/python3.10/site-packages/localtileserver/tileserver/rest.py", line 248, in get
    tile_source = self.get_tile_source()
  File "/Users/xinz/miniconda3/envs/enpt/lib/python3.10/site-packages/localtileserver/tileserver/rest.py", line 206, in get_tile_source
    return utilities.get_tile_source(filename, projection, encoding=encoding, style=sty)
  File "/Users/xinz/miniconda3/envs/enpt/lib/python3.10/site-packages/localtileserver/tileserver/utilities.py", line 79, in get_tile_source
    return large_image.open(str(path), projection=projection, style=style, encoding=encoding)
  File "/Users/xinz/miniconda3/envs/enpt/lib/python3.10/site-packages/large_image/tilesource/__init__.py", line 174, in open
    return getTileSource(*args, **kwargs)
  File "/Users/xinz/miniconda3/envs/enpt/lib/python3.10/site-packages/large_image/tilesource/__init__.py", line 162, in getTileSource
    return getTileSourceFromDict(AvailableTileSources, *args, **kwargs)
  File "/Users/xinz/miniconda3/envs/enpt/lib/python3.10/site-packages/large_image/tilesource/__init__.py", line 145, in getTileSourceFromDict
    sourceName = getSourceNameFromDict(availableSources, pathOrUri, *args, **kwargs)
  File "/Users/xinz/miniconda3/envs/enpt/lib/python3.10/site-packages/large_image/tilesource/__init__.py", line 130, in getSourceNameFromDict
    if availableSources[sourceName].canRead(pathOrUri, *args, **kwargs):
  File "/Users/xinz/miniconda3/envs/enpt/lib/python3.10/site-packages/large_image/tilesource/base.py", line 2883, in canRead
    cls(path, *args, **kwargs)
  File "/Users/xinz/miniconda3/envs/enpt/lib/python3.10/site-packages/large_image/cache_util/cache.py", line 229, in __call__
    raise exc
  File "/Users/xinz/miniconda3/envs/enpt/lib/python3.10/site-packages/large_image/cache_util/cache.py", line 220, in __call__
    instance = super().__call__(*args, **kwargs)
  File "/Users/xinz/miniconda3/envs/enpt/lib/python3.10/site-packages/large_image_source_gdal/__init__.py", line 139, in __init__
    self._initWithProjection(unitsPerPixel)
  File "/Users/xinz/miniconda3/envs/enpt/lib/python3.10/site-packages/large_image_source_gdal/__init__.py", line 245, in _initWithProjection
    self.levels = int(max(int(math.ceil(
ValueError: cannot convert float NaN to integer
---------------------------------------------------------------------------
HTTPError                                 Traceback (most recent call last)
Cell In[7], line 4
      1 import leafmap.foliumap as leafmap
      3 m = leafmap.Map()
----> 4 m.add_raster('[/Users/xinz/Downloads/test.tif](https://file+.vscode-resource.vscode-cdn.net/Users/xinz/Downloads/test.tif)', nodata=0)

File [~/miniconda3/envs/enpt/lib/python3.10/site-packages/leafmap/foliumap.py:405](https://file+.vscode-resource.vscode-cdn.net/Users/xinz/Documents/github/enmap/notebooks/~/miniconda3/envs/enpt/lib/python3.10/site-packages/leafmap/foliumap.py:405), in Map.add_raster(self, source, band, palette, vmin, vmax, nodata, attribution, layer_name, **kwargs)
    390 tile_layer, tile_client = get_local_tile_layer(
    391     source,
    392     band=band,
   (...)
    401     **kwargs,
    402 )
    403 self.add_layer(tile_layer)
--> 405 bounds = tile_client.bounds()  # [ymin, ymax, xmin, xmax]
    406 bounds = (
    407     bounds[2],
    408     bounds[0],
    409     bounds[3],
    410     bounds[1],
    411 )  # [minx, miny, maxx, maxy]
    412 self.zoom_to_bounds(bounds)

File [~/miniconda3/envs/enpt/lib/python3.10/site-packages/localtileserver/client.py:537](https://file+.vscode-resource.vscode-cdn.net/Users/xinz/Documents/github/enmap/notebooks/~/miniconda3/envs/enpt/lib/python3.10/site-packages/localtileserver/client.py:537), in RestfulTileClient.bounds(self, projection, return_polygon, return_wkt)
    531 def bounds(
    532     self, projection: str = "EPSG:4326", return_polygon: bool = False, return_wkt: bool = False
    533 ):
    534     r = requests.get(
    535         self.create_url(f"[/api/bounds](https://file+.vscode-resource.vscode-cdn.net/api/bounds)?units={projection}&projection={self.default_projection}")
    536     )
--> 537     r.raise_for_status()
    538     bounds = r.json()
    539     extent = (bounds["ymin"], bounds["ymax"], bounds["xmin"], bounds["xmax"])

File [~/miniconda3/envs/enpt/lib/python3.10/site-packages/requests/models.py:1021](https://file+.vscode-resource.vscode-cdn.net/Users/xinz/Documents/github/enmap/notebooks/~/miniconda3/envs/enpt/lib/python3.10/site-packages/requests/models.py:1021), in Response.raise_for_status(self)
   1016     http_error_msg = (
   1017         f"{self.status_code} Server Error: {reason} for url: {self.url}"
   1018     )
   1020 if http_error_msg:
-> 1021     raise HTTPError(http_error_msg, response=self)

HTTPError: 500 Server Error: INTERNAL SERVER ERROR for url: http://127.0.0.1:64727/api/bounds?units=EPSG:4326&projection=EPSG:3857&filename=%2FUsers%2Fxinz%2FDownloads%2Ftest.tif
```
</details>

**Comment by giswqs** [comment]
Leafmap uses localtileserver to display local raster images. This appears to be an issue with localtilesever. I would encourage you to open an issue at https://github.com/banesullivan/localtileserver. Alternatively, you can reproject the image to other commonly used projections. 

```python
from localtileserver import TileClient, get_leaflet_tile_layer
from ipyleaflet import Map

# Create a TileClient from a raster file
client = TileClient('test.tif')
# client = examples.get_san_francisco()  # use example data

# Create ipyleaflet TileLayer from that server
t = get_leaflet_tile_layer(client)
# Create ipyleaflet map, add tile layer, and display
m = Map(center=client.center(), zoom=client.default_zoom)
m.add_layer(t)
m
```
