### ISSUE TITLE
Failed to load model class 'LeafletMapModel' from module 'jupyter-leaflet'

### ISSUE THREAD

**Issue by Sanjanakaladharan** [opengeos/leafmap#610]
### Environment Information

-   leafmap version:
-   Python version:
-   Operating System:

### Description

iam trying to visulaise the map using the following code

### What I Did

m = leafmap.Map(center=[29.676840, -95.369222], zoom=19)
m.add_basemap("SATELLITE")
m

the output i got is 
[Open Browser Console for more detailed log - Double click to close this message]
Failed to load model class 'LeafletMapModel' from module 'jupyter-leaflet'
Error: No version of module jupyter-leaflet is registered
    at f.loadClass (http://3.110.43.132:8888/lab/extensions/@jupyter-widgets/jupyterlab-manager/static/134.a63a8d293fb35a52dc25.js?v=a63a8d293fb35a52dc25:1:74936)
    at f.loadModelClass (http://3.110.43.132:8888/lab/extensions/@jupyter-widgets/jupyterlab-manager/static/336.ebc7a55ea1768712771f.js?v=ebc7a55ea1768712771f:1:10729)
    at f._make_model (http://3.110.43.132:8888/lab/extensions/@jupyter-widgets/jupyterlab-manager/static/336.ebc7a55ea1768712771f.js?v=ebc7a55ea1768712771f:1:7517)
    at f.new_model (http://3.110.43.132:8888/lab/extensions/@jupyter-widgets/jupyterlab-manager/static/336.ebc7a55ea1768712771f.js?v=ebc7a55ea1768712771f:1:5137)
    at f.handle_comm_open (http://3.110.43.132:8888/lab/extensions/@jupyter-widgets/jupyterlab-manager/static/336.ebc7a55ea1768712771f.js?v=ebc7a55ea1768712771f:1:3894)
    at _handleCommOpen (http://3.110.43.132:8888/lab/extensions/@jupyter-widgets/jupyterlab-manager/static/134.a63a8d293fb35a52dc25.js?v=a63a8d293fb35a52dc25:1:73473)
    at v._handleCommOpen (http://3.110.43.132:8888/static/notebook/3676.bundle.js:1:30808)
    at async v._handleMessage (http://3.110.43.132:8888/static/notebook/3676.bundle.js:1:32702)

please help me to figure out what should i do

**Comment by giswqs** [comment]
This is an ipyleaflet installation issue. Try create a fresh conda env to install leafmap. 
https://leafmap.org/installation/#install-from-conda-forge
